package nix

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
)

// FlakeInput is one external flake declared in the managed state flake's
// inputs. It is a pure dependency declaration — a name and a flake ref —
// with no opinion on where the input is used. Making an input available is
// deliberately separate from wiring it into a workload or the host system;
// this type carries only what the inputs block needs.
type FlakeInput struct {
	// Name is the flake input name (referenced as inputs.<Name>). It obeys
	// the shared ValidateName path-safety rule.
	Name string
	// URL is the flake reference, e.g. "github:owner/repo".
	URL string
	// FollowsNixpkgs pins this input's own nixpkgs to the state flake's
	// nixpkgs input via inputs.nixpkgs.follows, avoiding a second nixpkgs
	// in the closure. When any input sets it, the state flake declares a
	// top-level nixpkgs input for them to follow.
	FollowsNixpkgs bool
}

// stateFlakeDescription is the description line of the generated flake.
const stateFlakeDescription = "nixbox-managed workloads (generated; do not edit by hand)"

// renderFlake produces state/flake.nix for the given flake inputs. The
// outputs are fixed — they expose the workload module set from
// modules/default.nix — so declaring an input never changes how the system
// is composed: it only makes the input available (and, once applied,
// locked) for a consumer to reference later. Inputs are emitted in name
// order so the file (and its lock) is stable across runs.
//
// agenix is the one exception to "declared inputs are never referenced":
// when secrets exist (withAgenix), nixbox declares the agenix input itself
// and imports its NixOS module into nixosModules.default, since the
// age.secrets declarations in modules/secrets.nix need its options. This
// is deliberately lazy — a secretless system keeps an input-free (or
// user-inputs-only) flake and never fetches agenix. A user-declared input
// named "agenix" takes precedence over the built-in pin.
func renderFlake(inputs []FlakeInput, withAgenix bool) string {
	sorted := append([]FlakeInput(nil), inputs...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	userAgenix := false
	for _, in := range sorted {
		if in.Name == "agenix" {
			userAgenix = true
		}
	}
	ownAgenix := withAgenix && !userAgenix

	needNixpkgs := ownAgenix // the built-in agenix pin follows nixpkgs
	for _, in := range sorted {
		if in.FollowsNixpkgs {
			needNixpkgs = true
			break
		}
	}

	var b strings.Builder
	b.WriteString("# Generated by nixbox; do not edit by hand.\n{\n")
	fmt.Fprintf(&b, "  description = %s;\n\n", nixStr(stateFlakeDescription))

	b.WriteString("  inputs = {\n")
	if needNixpkgs {
		// A pinned nixpkgs the following inputs share. Point
		// nixbox-state.inputs.nixpkgs.follows at the host's nixpkgs in the
		// host flake to collapse this onto a single nixpkgs (see README).
		b.WriteString("    nixpkgs.url = \"github:NixOS/nixpkgs/nixos-unstable\";\n")
	}
	if ownAgenix {
		// Declared by nixbox because secrets exist; agenix decrypts them
		// during activation. darwin/home-manager are agenix extras this
		// module set never evaluates — follows = "" drops them from the
		// lock so declaring a secret doesn't fetch either.
		b.WriteString("    agenix = {\n")
		b.WriteString("      url = \"github:ryantm/agenix\";\n")
		b.WriteString("      inputs.nixpkgs.follows = \"nixpkgs\";\n")
		b.WriteString("      inputs.darwin.follows = \"\";\n")
		b.WriteString("      inputs.home-manager.follows = \"\";\n")
		b.WriteString("    };\n")
	}
	for _, in := range sorted {
		key := nixAttrName(in.Name)
		if in.FollowsNixpkgs {
			fmt.Fprintf(&b, "    %s = { url = %s; inputs.nixpkgs.follows = \"nixpkgs\"; };\n", key, nixStr(in.URL))
		} else {
			fmt.Fprintf(&b, "    %s.url = %s;\n", key, nixStr(in.URL))
		}
	}
	b.WriteString("  };\n\n")

	// Outputs expose the workload composition and thread the declared flake
	// inputs down to every workload, so a workload.nix can import a module
	// from an input (e.g. a flake declared in the Flakes tab). Inputs a
	// workload doesn't reference are still just locked, never built.
	//
	// Containers receive the inputs as the `flakeInputs` module arg (their
	// type modules apply lib.toFunction; the arg only ever feeds *config*).
	// Host services need more care: each one is a system-level module whose
	// `imports` may reference an input, and NixOS forbids module args in
	// imports (infinite recursion — imports resolve before the arg fixpoint).
	// So their { flakeInputs }: wrapper is applied HERE, in outputs scope,
	// where `inputs` is plain data. builtins.functionArgs disambiguates the
	// wrapper from an ordinary module function ({ config, pkgs, ... }: …),
	// which is passed to the module system untouched.
	baseImports := "[ ./modules/default.nix ]"
	if withAgenix {
		// The agenix module declares the age.* options that
		// modules/secrets.nix (imported under the same secrets-exist
		// condition) defines values for.
		baseImports = "[ ./modules/default.nix inputs.agenix.nixosModules.default ]"
	}
	fmt.Fprintf(&b, `  outputs = { self, ... }@inputs: {
    nixosModules.default = { ... }: {
      imports = %s ++ (map
        (path:
          let v = import path;
          in if builtins.isFunction v && (builtins.functionArgs v) ? flakeInputs
             then v { flakeInputs = inputs; }
             else v)
        (builtins.attrValues ((import ./index.nix).hostServices or { })));
      _module.args.flakeInputs = inputs;
    };
  };
}
`, baseImports)
	return b.String()
}

// WriteFlake regenerates state/flake.nix from the declared flake inputs. It
// mirrors WriteIndex: the server calls it at apply time from the input
// registry, and Init bootstraps an input-free flake when none exists.
// withAgenix must mirror "the index declares secrets" — the caller derives
// both from the same store state. Changing inputs invalidates the lock;
// the pipeline re-locks before rebuilding.
func (f *StateFlake) WriteFlake(inputs []FlakeInput, withAgenix bool) error {
	return writeFileAtomic(filepath.Join(f.Dir, "flake.nix"), []byte(renderFlake(inputs, withAgenix)))
}

// nixStr renders a Nix double-quoted string literal, escaping the
// characters that are special inside one.
func nixStr(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, `${`, `\${`)
	return `"` + r.Replace(s) + `"`
}
