package nix

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRenderFlakeNoInputs(t *testing.T) {
	got := renderFlake(nil, false)
	want := `# Generated by nixbox; do not edit by hand.
{
  description = "nixbox-managed workloads (generated; do not edit by hand)";

  inputs = {
  };

  outputs = { self, ... }@inputs: {
    nixosModules.default = { ... }: {
      imports = [ ./modules/default.nix ] ++ (map
        (path:
          let v = import path;
          in if builtins.isFunction v && (builtins.functionArgs v) ? flakeInputs
             then v { flakeInputs = inputs; }
             else v)
        (builtins.attrValues ((import ./index.nix).hostServices or { })));
      _module.args.flakeInputs = inputs;
    };
  };
}
`
	if got != want {
		t.Errorf("renderFlake(nil, false):\n%s\nwant:\n%s", got, want)
	}
}

func TestRenderFlakeInputs(t *testing.T) {
	// Out of order and mixed follows to exercise sorting and the shared
	// nixpkgs input. The outputs stay fixed — inputs are declared, not used.
	got := renderFlake([]FlakeInput{
		{Name: "nixflix", URL: "github:owner/nixflix", FollowsNixpkgs: true},
		{Name: "bare", URL: "github:owner/bare"},
	}, false)
	want := `# Generated by nixbox; do not edit by hand.
{
  description = "nixbox-managed workloads (generated; do not edit by hand)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    bare.url = "github:owner/bare";
    nixflix = { url = "github:owner/nixflix"; inputs.nixpkgs.follows = "nixpkgs"; };
  };

  outputs = { self, ... }@inputs: {
    nixosModules.default = { ... }: {
      imports = [ ./modules/default.nix ] ++ (map
        (path:
          let v = import path;
          in if builtins.isFunction v && (builtins.functionArgs v) ? flakeInputs
             then v { flakeInputs = inputs; }
             else v)
        (builtins.attrValues ((import ./index.nix).hostServices or { })));
      _module.args.flakeInputs = inputs;
    };
  };
}
`
	if got != want {
		t.Errorf("renderFlake:\n%s\nwant:\n%s", got, want)
	}
}

// TestRenderFlakeNoFollows: with nothing following nixpkgs the state flake
// declares no nixpkgs input (keeps the closure lean).
func TestRenderFlakeNoFollows(t *testing.T) {
	got := renderFlake([]FlakeInput{{Name: "svc", URL: "github:owner/svc"}}, false)
	if strings.Contains(got, "nixpkgs") {
		t.Errorf("expected no nixpkgs input when nothing follows:\n%s", got)
	}
}

// TestInitDoesNotClobberFlake: a generated flake carrying inputs must
// survive a second Init (service restart) — Init only seeds flake.nix when
// absent.
func TestInitDoesNotClobberFlake(t *testing.T) {
	f := &StateFlake{Dir: t.TempDir()}
	if err := f.Init(); err != nil {
		t.Fatal(err)
	}
	if err := f.WriteFlake([]FlakeInput{{Name: "nixflix", URL: "github:owner/nixflix"}}, false); err != nil {
		t.Fatal(err)
	}
	if err := f.Init(); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(f.Dir, "flake.nix"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "github:owner/nixflix") {
		t.Errorf("Init clobbered a flake with inputs:\n%s", got)
	}
}
