package nix

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
)

// FlakeInput is one external flake declared in the managed state flake's
// inputs. It is a pure dependency declaration — a name and a flake ref —
// with no opinion on where the input is used. Making an input available is
// deliberately separate from wiring it into a workload or the host system;
// this type carries only what the inputs block needs.
type FlakeInput struct {
	// Name is the flake input name (referenced as inputs.<Name>). It obeys
	// the shared ValidateName path-safety rule.
	Name string
	// URL is the flake reference, e.g. "github:owner/repo".
	URL string
	// FollowsNixpkgs pins this input's own nixpkgs to the state flake's
	// nixpkgs input via inputs.nixpkgs.follows, avoiding a second nixpkgs
	// in the closure. When any input sets it, the state flake declares a
	// top-level nixpkgs input for them to follow.
	FollowsNixpkgs bool
}

// stateFlakeDescription is the description line of the generated flake.
const stateFlakeDescription = "nixbox-managed workloads (generated; do not edit by hand)"

// renderFlake produces state/flake.nix for the given flake inputs. The
// outputs are fixed — they expose the workload module set from
// modules/default.nix — so declaring an input never changes how the system
// is composed: it only makes the input available (and, once applied,
// locked) for a consumer to reference later. Inputs are emitted in name
// order so the file (and its lock) is stable across runs.
func renderFlake(inputs []FlakeInput) string {
	sorted := append([]FlakeInput(nil), inputs...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	needNixpkgs := false
	for _, in := range sorted {
		if in.FollowsNixpkgs {
			needNixpkgs = true
			break
		}
	}

	var b strings.Builder
	b.WriteString("# Generated by nixbox; do not edit by hand.\n{\n")
	fmt.Fprintf(&b, "  description = %s;\n\n", nixStr(stateFlakeDescription))

	b.WriteString("  inputs = {\n")
	if needNixpkgs {
		// A pinned nixpkgs the following inputs share. Point
		// nixbox-state.inputs.nixpkgs.follows at the host's nixpkgs in the
		// host flake to collapse this onto a single nixpkgs (see README).
		b.WriteString("    nixpkgs.url = \"github:NixOS/nixpkgs/nixos-unstable\";\n")
	}
	for _, in := range sorted {
		key := nixAttrName(in.Name)
		if in.FollowsNixpkgs {
			fmt.Fprintf(&b, "    %s = { url = %s; inputs.nixpkgs.follows = \"nixpkgs\"; };\n", key, nixStr(in.URL))
		} else {
			fmt.Fprintf(&b, "    %s.url = %s;\n", key, nixStr(in.URL))
		}
	}
	b.WriteString("  };\n\n")

	// Fixed outputs: only the workload composition. Declared inputs are
	// intentionally unreferenced here — where they get used is handled
	// separately — but Nix still locks them.
	b.WriteString("  outputs = { self, ... }: {\n")
	b.WriteString("    nixosModules.default = import ./modules/default.nix;\n")
	b.WriteString("  };\n}\n")
	return b.String()
}

// WriteFlake regenerates state/flake.nix from the declared flake inputs. It
// mirrors WriteIndex: the server calls it at apply time from the input
// registry, and Init bootstraps an input-free flake when none exists.
// Changing inputs invalidates the lock; the pipeline re-locks before
// rebuilding.
func (f *StateFlake) WriteFlake(inputs []FlakeInput) error {
	return writeFileAtomic(filepath.Join(f.Dir, "flake.nix"), []byte(renderFlake(inputs)))
}

// nixStr renders a Nix double-quoted string literal, escaping the
// characters that are special inside one.
func nixStr(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, `${`, `\${`)
	return `"` + r.Replace(s) + `"`
}
