// Package nix implements nixbox's integration with the Nix toolchain:
// generation of the managed state flake, the rebuild pipeline, and
// expression validation.
//
// The state flake (<stateDir>/state) is a self-contained flake exporting
// nixosModules.default. The host flake references it as a path input; a
// rebuild picks up changes after `nix flake update nixbox-state`.
package nix

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// Workload type IDs stored in workloads.type. Each corresponds to a
// registered WorkloadType (see types.go); adding another kind (microvm, …)
// is a new const plus its Register call — no branch here.
const (
	WorkloadTypeContainer   = "nixos-container"
	WorkloadTypeOCI         = "oci-container"
	WorkloadTypeHostService = "host-service"
)

// flake.nix is generated from the declared flake inputs (see flakes.go).
// With no inputs it is input-free — adding a workload *type* never touches
// inputs, so the "no re-lock on type add" property holds; only declaring a
// flake input (a new dependency) changes inputs and forces a re-lock, which
// is expected.

// A flake with no inputs still needs a lock file for path-input
// consumers; this is exactly what `nix flake lock` produces. It seeds the
// lock on first init; once inputs are declared the pipeline re-locks.
const stateFlakeLock = `{
  "nodes": {
    "root": {}
  },
  "root": "root",
  "version": 7
}
`

// hostPortsModule is the shared, type-agnostic base module: it opens the
// union of host firewall ports every enabled workload asked for. Kept
// separate from the per-type modules because the firewall merge is the
// same regardless of workload type.
const hostPortsModule = `{ ... }:

let
  index = import ../index.nix;
in
{
  # Host firewall ports declared by enabled workloads. Shared-namespace
  # containers serve on the host's network stack, so the port they listen
  # on must be opened here rather than inside the workload. ` + "`or [ ]`" + ` keeps
  # this evaluating against index files generated before host ports existed.
  networking.firewall.allowedTCPPorts = index.hostPorts.tcp or [ ];
  networking.firewall.allowedUDPPorts = index.hostPorts.udp or [ ];
}
`

// StateFlake manages the on-disk layout of the generated flake.
type StateFlake struct {
	// Dir is the root of the state flake (<stateDir>/state).
	Dir string
}

// Init seeds the static files of the state flake. It is idempotent and
// never touches workloads/ or index.nix if they already exist, so it is
// safe to run on every service start.
func (f *StateFlake) Init() error {
	for _, d := range []string{f.Dir, filepath.Join(f.Dir, "modules"), filepath.Join(f.Dir, "workloads"), filepath.Join(f.Dir, "secrets")} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			return err
		}
	}
	// The module files are regenerated on every Init so they always reflect
	// the current registered type set.
	static := map[string]string{
		"modules/hostports.nix": hostPortsModule,
		"modules/secrets.nix":   secretsModule,
		"modules/default.nix":   modulesDefault(),
	}
	// One static NixOS module per registered workload type. A type with no
	// ModuleFile (host-service) is composed by the generated flake output
	// instead — its workloads are system-level modules whose imports may
	// reference flake inputs, which a static module cannot thread through
	// (module args are unusable in `imports`; see renderFlake).
	for _, wt := range RegisteredTypes() {
		if wt.ModuleFile != "" {
			static[wt.ModuleFile] = wt.Module
		}
	}
	for name, content := range static {
		if err := writeFileAtomic(filepath.Join(f.Dir, name), []byte(content)); err != nil {
			return err
		}
	}
	// flake.nix and flake.lock are generated from the enabled services and
	// re-locked by the pipeline, so Init only seeds them when absent — it
	// must never clobber a flake that already carries service inputs and a
	// matching lock.
	if _, err := os.Stat(filepath.Join(f.Dir, "flake.nix")); os.IsNotExist(err) {
		if err := f.WriteFlake(nil, false); err != nil {
			return err
		}
	}
	if _, err := os.Stat(filepath.Join(f.Dir, "flake.lock")); os.IsNotExist(err) {
		if err := writeFileAtomic(filepath.Join(f.Dir, "flake.lock"), []byte(stateFlakeLock)); err != nil {
			return err
		}
	}
	// An index must always exist for the flake to evaluate.
	if _, err := os.Stat(filepath.Join(f.Dir, "index.nix")); os.IsNotExist(err) {
		if err := f.WriteIndex(nil, nil); err != nil {
			return err
		}
	}
	return nil
}

// modulesDefault renders modules/default.nix: the module list imported by
// the flake output. Regenerated on every Init so it always reflects the
// current registered type set. The shared hostPorts module comes first,
// then one module per workload type in registration order, then —
// conditionally — the secrets module.
func modulesDefault() string {
	var b strings.Builder
	b.WriteString("# Generated by nixbox; do not edit.\n{\n  imports = [\n    ./hostports.nix\n")
	for _, wt := range RegisteredTypes() {
		if wt.ModuleFile != "" {
			fmt.Fprintf(&b, "    ./%s\n", filepath.Base(wt.ModuleFile))
		}
	}
	// secrets.nix defines age.secrets, options that only exist once the
	// generated flake imports agenix — which it does exactly when secrets
	// exist (see renderFlake). Gate the import on the same index-derived
	// condition so a secretless system never requires the age options.
	b.WriteString("  ]\n  ++ (if ((import ../index.nix).secrets or { }) == { } then [ ] else [ ./secrets.nix ]);\n}\n")
	return b.String()
}

// IndexEntry is one enabled workload to expose to the host system.
type IndexEntry struct {
	Name  string
	Type  string
	Ports []HostPort // host firewall ports to open for this workload
}

// WriteIndex regenerates index.nix from the enabled workloads and the
// declared secrets: one name→path map per registered workload type
// (keyed by the type's IndexKey), the union of host ports every enabled
// workload asked to open split by protocol, and one entry per secret
// (ciphertext path, decrypted-file identity, and delivery mounts).
// Entries of an unregistered type are excluded entirely — they map to no
// module and open no ports.
func (f *StateFlake) WriteIndex(entries []IndexEntry, secrets []IndexSecret) error {
	types := RegisteredTypes()
	namesByKey := make(map[string][]string, len(types))
	for _, wt := range types {
		namesByKey[wt.IndexKey] = nil // ensure an (empty) section is emitted
	}
	tcpSeen, udpSeen := map[int]bool{}, map[int]bool{}
	var tcp, udp []int
	for _, e := range entries {
		wt, ok := Lookup(e.Type)
		if !ok {
			continue
		}
		namesByKey[wt.IndexKey] = append(namesByKey[wt.IndexKey], e.Name)
		for _, p := range e.Ports {
			switch p.Proto {
			case "udp":
				if !udpSeen[p.Port] {
					udpSeen[p.Port] = true
					udp = append(udp, p.Port)
				}
			default:
				if !tcpSeen[p.Port] {
					tcpSeen[p.Port] = true
					tcp = append(tcp, p.Port)
				}
			}
		}
	}
	for k := range namesByKey {
		sort.Strings(namesByKey[k])
	}
	sort.Ints(tcp)
	sort.Ints(udp)

	var b strings.Builder
	b.WriteString("# Generated by nixbox; do not edit.\n{\n")
	for _, wt := range types {
		fmt.Fprintf(&b, "  %s = {\n", wt.IndexKey)
		for _, name := range namesByKey[wt.IndexKey] {
			fmt.Fprintf(&b, "    %s = ./workloads/%s/workload.nix;\n", nixAttrName(name), name)
		}
		b.WriteString("  };\n")
	}
	b.WriteString("  hostPorts = {\n")
	fmt.Fprintf(&b, "    tcp = %s;\n", nixIntList(tcp))
	fmt.Fprintf(&b, "    udp = %s;\n", nixIntList(udp))
	b.WriteString("  };\n")
	writeIndexSecrets(&b, secrets)
	b.WriteString("}\n")
	return writeFileAtomic(filepath.Join(f.Dir, "index.nix"), []byte(b.String()))
}

// writeIndexSecrets renders the secrets section of index.nix. Sorted by
// name (and mount keys/names sorted) so the file is stable across runs;
// only non-empty mount lists are emitted, and consumers use `or [ ]`.
func writeIndexSecrets(b *strings.Builder, secrets []IndexSecret) {
	sorted := append([]IndexSecret(nil), secrets...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })
	b.WriteString("  secrets = {\n")
	for _, s := range sorted {
		fmt.Fprintf(b, "    %s = {\n", nixAttrName(s.Name))
		fmt.Fprintf(b, "      file = ./secrets/%s.age;\n", s.Name)
		fmt.Fprintf(b, "      owner = %s;\n", nixStr(s.Owner))
		fmt.Fprintf(b, "      group = %s;\n", nixStr(s.Group))
		fmt.Fprintf(b, "      mode = %s;\n", nixStr(s.Mode))
		b.WriteString("      mounts = {\n")
		keys := make([]string, 0, len(s.Mounts))
		for k, names := range s.Mounts {
			if len(names) > 0 {
				keys = append(keys, k)
			}
		}
		sort.Strings(keys)
		for _, k := range keys {
			names := append([]string(nil), s.Mounts[k]...)
			sort.Strings(names)
			quoted := make([]string, len(names))
			for i, n := range names {
				quoted[i] = nixStr(n)
			}
			fmt.Fprintf(b, "        %s = [ %s ];\n", k, strings.Join(quoted, " "))
		}
		b.WriteString("      };\n    };\n")
	}
	b.WriteString("  };\n")
}

// nixIntList renders a Nix list literal of integers, e.g. "[ 80 443 ]"
// or "[ ]" when empty.
func nixIntList(xs []int) string {
	if len(xs) == 0 {
		return "[ ]"
	}
	parts := make([]string, len(xs))
	for i, x := range xs {
		parts[i] = strconv.Itoa(x)
	}
	return "[ " + strings.Join(parts, " ") + " ]"
}

// WriteWorkload writes a workload's Nix expression to its slot in the
// state flake.
func (f *StateFlake) WriteWorkload(name, content string) error {
	if err := ValidateName(name); err != nil {
		return err
	}
	dir := filepath.Join(f.Dir, "workloads", name)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	return writeFileAtomic(filepath.Join(dir, "workload.nix"), []byte(content))
}

// ReadWorkload returns the current on-disk expression for a workload.
func (f *StateFlake) ReadWorkload(name string) (string, error) {
	if err := ValidateName(name); err != nil {
		return "", err
	}
	b, err := os.ReadFile(filepath.Join(f.Dir, "workloads", name, "workload.nix"))
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// RemoveWorkload deletes a workload's directory from the state flake.
// The caller must regenerate the index first so the flake never
// references a missing file.
func (f *StateFlake) RemoveWorkload(name string) error {
	if err := ValidateName(name); err != nil {
		return err
	}
	return os.RemoveAll(filepath.Join(f.Dir, "workloads", name))
}

// nameRe is the shared filesystem/path-safety rule enforced wherever a
// name reaches disk (WriteWorkload, ReadWorkload, lookupWorkload): lower
// DNS-label charset, no leading/trailing dash, 1-63 bytes. It stays
// permissive enough for any workload type; tighter, type-specific limits
// (e.g. the 11-char nspawn interface cap for nixos-containers) live in the
// per-type WorkloadType.ValidateName, layered on top of this check.
var nameRe = regexp.MustCompile(`^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$`)

func ValidateName(name string) error {
	if !nameRe.MatchString(name) {
		return fmt.Errorf("invalid workload name %q: must be 1-63 characters of [a-z0-9-], not starting or ending with -", name)
	}
	return nil
}

// maxDisplayName bounds the optional friendly name. It never reaches the
// Nix eval path or a filesystem path (only the ID does), so the only
// constraints are a sane length and no control characters that would
// mangle the rendered page.
const maxDisplayName = 60

// ValidateDisplayName checks the optional friendly label. An empty string
// is valid (the UI falls back to the ID).
func ValidateDisplayName(name string) error {
	if len(name) > maxDisplayName {
		return fmt.Errorf("display name too long: %d characters (max %d)", len(name), maxDisplayName)
	}
	for _, r := range name {
		if r == '\n' || r == '\r' || r == '\t' || (r < 0x20) {
			return fmt.Errorf("display name must not contain control characters")
		}
	}
	return nil
}

// nixAttrName quotes the attribute if it isn't a valid bare Nix
// identifier (e.g. names starting with a digit, or containing -).
func nixAttrName(name string) string {
	if regexp.MustCompile(`^[a-zA-Z_][a-zA-Z0-9_'-]*$`).MatchString(name) {
		return name
	}
	return `"` + name + `"`
}

// writeFileAtomic writes via a temp file + rename so a crash mid-write
// never leaves a truncated file for Nix to evaluate.
func writeFileAtomic(path string, data []byte) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), ".tmp-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Chmod(0o644); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}
