// Package nix implements nixbox's integration with the Nix toolchain:
// generation of the managed state flake, the rebuild pipeline, and
// expression validation.
//
// The state flake (<stateDir>/state) is a self-contained flake exporting
// nixosModules.default. The host flake references it as a path input; a
// rebuild picks up changes after `nix flake update nixbox-state`.
package nix

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// WorkloadTypeContainer is the built-in workload type: a NixOS
// declarative container. Additional types (oci-container, microvm) are
// added by registering a WorkloadType (see types.go) — no branch here.
const WorkloadTypeContainer = "nixos-container"

// The flake output is fixed boilerplate; the actual module set lives in
// the generated modules/default.nix, so adding a workload type never
// rewrites the flake (and never re-locks it).
const stateFlakeNix = `{
  description = "nixbox-managed workloads (generated; do not edit by hand)";

  outputs = { self }: {
    nixosModules.default = import ./modules/default.nix;
  };
}
`

// A flake with no inputs still needs a lock file for path-input
// consumers; this is exactly what `nix flake lock` produces.
const stateFlakeLock = `{
  "nodes": {
    "root": {}
  },
  "root": "root",
  "version": 7
}
`

// hostPortsModule is the shared, type-agnostic base module: it opens the
// union of host firewall ports every enabled workload asked for. Kept
// separate from the per-type modules because the firewall merge is the
// same regardless of workload type.
const hostPortsModule = `{ ... }:

let
  index = import ../index.nix;
in
{
  # Host firewall ports declared by enabled workloads. Shared-namespace
  # containers serve on the host's network stack, so the port they listen
  # on must be opened here rather than inside the workload. ` + "`or [ ]`" + ` keeps
  # this evaluating against index files generated before host ports existed.
  networking.firewall.allowedTCPPorts = index.hostPorts.tcp or [ ];
  networking.firewall.allowedUDPPorts = index.hostPorts.udp or [ ];
}
`

// StateFlake manages the on-disk layout of the generated flake.
type StateFlake struct {
	// Dir is the root of the state flake (<stateDir>/state).
	Dir string
}

// Init seeds the static files of the state flake. It is idempotent and
// never touches workloads/ or index.nix if they already exist, so it is
// safe to run on every service start.
func (f *StateFlake) Init() error {
	for _, d := range []string{f.Dir, filepath.Join(f.Dir, "modules"), filepath.Join(f.Dir, "workloads")} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			return err
		}
	}
	static := map[string]string{
		"flake.nix":             stateFlakeNix,
		"flake.lock":            stateFlakeLock,
		"modules/hostports.nix": hostPortsModule,
		"modules/default.nix":   modulesDefault(),
	}
	// One static NixOS module per registered workload type.
	for _, wt := range RegisteredTypes() {
		static[wt.ModuleFile] = wt.Module
	}
	for name, content := range static {
		if err := writeFileAtomic(filepath.Join(f.Dir, name), []byte(content)); err != nil {
			return err
		}
	}
	// An index must always exist for the flake to evaluate.
	indexPath := filepath.Join(f.Dir, "index.nix")
	if _, err := os.Stat(indexPath); os.IsNotExist(err) {
		if err := f.WriteIndex(nil); err != nil {
			return err
		}
	}
	return nil
}

// modulesDefault renders modules/default.nix: the module list imported by
// the flake output. Regenerated on every Init so it always reflects the
// current registered type set. The shared hostPorts module comes first,
// then one module per workload type in registration order.
func modulesDefault() string {
	var b strings.Builder
	b.WriteString("# Generated by nixbox; do not edit.\n{\n  imports = [\n    ./hostports.nix\n")
	for _, wt := range RegisteredTypes() {
		fmt.Fprintf(&b, "    ./%s\n", filepath.Base(wt.ModuleFile))
	}
	b.WriteString("  ];\n}\n")
	return b.String()
}

// IndexEntry is one enabled workload to expose to the host system.
type IndexEntry struct {
	Name  string
	Type  string
	Ports []HostPort // host firewall ports to open for this workload
}

// WriteIndex regenerates index.nix from the enabled workloads: one
// name→path map per registered workload type (keyed by the type's
// IndexKey) plus the union of host ports every enabled workload asked to
// open, split by protocol. Entries of an unregistered type are excluded
// entirely — they map to no module and open no ports.
func (f *StateFlake) WriteIndex(entries []IndexEntry) error {
	types := RegisteredTypes()
	namesByKey := make(map[string][]string, len(types))
	for _, wt := range types {
		namesByKey[wt.IndexKey] = nil // ensure an (empty) section is emitted
	}
	tcpSeen, udpSeen := map[int]bool{}, map[int]bool{}
	var tcp, udp []int
	for _, e := range entries {
		wt, ok := Lookup(e.Type)
		if !ok {
			continue
		}
		namesByKey[wt.IndexKey] = append(namesByKey[wt.IndexKey], e.Name)
		for _, p := range e.Ports {
			switch p.Proto {
			case "udp":
				if !udpSeen[p.Port] {
					udpSeen[p.Port] = true
					udp = append(udp, p.Port)
				}
			default:
				if !tcpSeen[p.Port] {
					tcpSeen[p.Port] = true
					tcp = append(tcp, p.Port)
				}
			}
		}
	}
	for k := range namesByKey {
		sort.Strings(namesByKey[k])
	}
	sort.Ints(tcp)
	sort.Ints(udp)

	var b strings.Builder
	b.WriteString("# Generated by nixbox; do not edit.\n{\n")
	for _, wt := range types {
		fmt.Fprintf(&b, "  %s = {\n", wt.IndexKey)
		for _, name := range namesByKey[wt.IndexKey] {
			fmt.Fprintf(&b, "    %s = ./workloads/%s/workload.nix;\n", nixAttrName(name), name)
		}
		b.WriteString("  };\n")
	}
	b.WriteString("  hostPorts = {\n")
	fmt.Fprintf(&b, "    tcp = %s;\n", nixIntList(tcp))
	fmt.Fprintf(&b, "    udp = %s;\n", nixIntList(udp))
	b.WriteString("  };\n}\n")
	return writeFileAtomic(filepath.Join(f.Dir, "index.nix"), []byte(b.String()))
}

// nixIntList renders a Nix list literal of integers, e.g. "[ 80 443 ]"
// or "[ ]" when empty.
func nixIntList(xs []int) string {
	if len(xs) == 0 {
		return "[ ]"
	}
	parts := make([]string, len(xs))
	for i, x := range xs {
		parts[i] = strconv.Itoa(x)
	}
	return "[ " + strings.Join(parts, " ") + " ]"
}

// WriteWorkload writes a workload's Nix expression to its slot in the
// state flake.
func (f *StateFlake) WriteWorkload(name, content string) error {
	if err := ValidateName(name); err != nil {
		return err
	}
	dir := filepath.Join(f.Dir, "workloads", name)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	return writeFileAtomic(filepath.Join(dir, "workload.nix"), []byte(content))
}

// ReadWorkload returns the current on-disk expression for a workload.
func (f *StateFlake) ReadWorkload(name string) (string, error) {
	if err := ValidateName(name); err != nil {
		return "", err
	}
	b, err := os.ReadFile(filepath.Join(f.Dir, "workloads", name, "workload.nix"))
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// RemoveWorkload deletes a workload's directory from the state flake.
// The caller must regenerate the index first so the flake never
// references a missing file.
func (f *StateFlake) RemoveWorkload(name string) error {
	if err := ValidateName(name); err != nil {
		return err
	}
	return os.RemoveAll(filepath.Join(f.Dir, "workloads", name))
}

// nameRe: systemd-nspawn creates a "ve-<name>" host interface for
// private networking; interface names cap at 15 bytes, leaving 11 for
// the container name. Same limit NixOS enforces on containers.<name>.
//
// ValidateName doubles as the filesystem/path-safety check used wherever
// a name reaches disk (WriteWorkload, ReadWorkload, lookupWorkload), so it
// stays strict enough to be safe for any type. The nixos-container type
// also uses it as its type-specific WorkloadType.ValidateName; a future
// type with a looser naming rule would split the two — relax the shared
// path check to charset-only and enforce length in the per-type func.
var nameRe = regexp.MustCompile(`^[a-z0-9]([a-z0-9-]{0,9}[a-z0-9])?$`)

func ValidateName(name string) error {
	if !nameRe.MatchString(name) {
		return fmt.Errorf("invalid workload name %q: must be 1-11 characters of [a-z0-9-], not starting or ending with -", name)
	}
	return nil
}

// maxDisplayName bounds the optional friendly name. It never reaches the
// Nix eval path or a filesystem path (only the ID does), so the only
// constraints are a sane length and no control characters that would
// mangle the rendered page.
const maxDisplayName = 60

// ValidateDisplayName checks the optional friendly label. An empty string
// is valid (the UI falls back to the ID).
func ValidateDisplayName(name string) error {
	if len(name) > maxDisplayName {
		return fmt.Errorf("display name too long: %d characters (max %d)", len(name), maxDisplayName)
	}
	for _, r := range name {
		if r == '\n' || r == '\r' || r == '\t' || (r < 0x20) {
			return fmt.Errorf("display name must not contain control characters")
		}
	}
	return nil
}

// nixAttrName quotes the attribute if it isn't a valid bare Nix
// identifier (e.g. names starting with a digit, or containing -).
func nixAttrName(name string) string {
	if regexp.MustCompile(`^[a-zA-Z_][a-zA-Z0-9_'-]*$`).MatchString(name) {
		return name
	}
	return `"` + name + `"`
}

// writeFileAtomic writes via a temp file + rename so a crash mid-write
// never leaves a truncated file for Nix to evaluate.
func writeFileAtomic(path string, data []byte) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), ".tmp-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Chmod(0o644); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}
