package nix

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestInitIdempotent(t *testing.T) {
	f := &StateFlake{Dir: t.TempDir()}
	if err := f.Init(); err != nil {
		t.Fatal(err)
	}
	// A regenerated index must survive a second Init (service restart).
	if err := f.WriteIndex([]IndexEntry{{Name: "web", Type: WorkloadTypeContainer}}, nil); err != nil {
		t.Fatal(err)
	}
	if err := f.Init(); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(f.Dir, "index.nix"))
	if err != nil {
		t.Fatal(err)
	}
	want := `# Generated by nixbox; do not edit.
{
  containers = {
    web = ./workloads/web/workload.nix;
  };
  ociContainers = {
  };
  hostServices = {
  };
  hostPorts = {
    tcp = [ ];
    udp = [ ];
  };
  secrets = {
  };
}
`
	if string(got) != want {
		t.Errorf("index.nix after re-init:\n%s\nwant:\n%s", got, want)
	}
}

func TestWriteIndex(t *testing.T) {
	f := &StateFlake{Dir: t.TempDir()}
	if err := f.Init(); err != nil {
		t.Fatal(err)
	}
	entries := []IndexEntry{
		{Name: "zeta", Type: WorkloadTypeContainer},
		{Name: "alpha", Type: WorkloadTypeContainer},
		{Name: "web", Type: WorkloadTypeOCI},              // OCI: its own section
		{Name: "jellyfin", Type: WorkloadTypeHostService}, // uncontained: its own section
		{Name: "ghost", Type: "microvm"},                  // unregistered: excluded
	}
	if err := f.WriteIndex(entries, nil); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(f.Dir, "index.nix"))
	if err != nil {
		t.Fatal(err)
	}
	want := `# Generated by nixbox; do not edit.
{
  containers = {
    alpha = ./workloads/alpha/workload.nix;
    zeta = ./workloads/zeta/workload.nix;
  };
  ociContainers = {
    web = ./workloads/web/workload.nix;
  };
  hostServices = {
    jellyfin = ./workloads/jellyfin/workload.nix;
  };
  hostPorts = {
    tcp = [ ];
    udp = [ ];
  };
  secrets = {
  };
}
`
	if string(got) != want {
		t.Errorf("index.nix:\n%s\nwant:\n%s", got, want)
	}
}

func TestWriteIndexHostPorts(t *testing.T) {
	f := &StateFlake{Dir: t.TempDir()}
	if err := f.Init(); err != nil {
		t.Fatal(err)
	}
	entries := []IndexEntry{
		{Name: "web", Type: WorkloadTypeContainer, Ports: []HostPort{
			{Port: 8080, Proto: "tcp"}, {Port: 443, Proto: "tcp"},
		}},
		{Name: "dns", Type: WorkloadTypeContainer, Ports: []HostPort{
			{Port: 53, Proto: "udp"}, {Port: 443, Proto: "tcp"}, // 443 dup across workloads
		}},
		{Name: "app", Type: WorkloadTypeOCI, Ports: []HostPort{
			{Port: 9999, Proto: "tcp"}, // OCI publishes a host port: unioned in
		}},
		{Name: "ghost", Type: "microvm", Ports: []HostPort{
			{Port: 1234, Proto: "tcp"}, // unregistered type: excluded entirely
		}},
	}
	if err := f.WriteIndex(entries, nil); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(f.Dir, "index.nix"))
	if err != nil {
		t.Fatal(err)
	}
	want := `# Generated by nixbox; do not edit.
{
  containers = {
    dns = ./workloads/dns/workload.nix;
    web = ./workloads/web/workload.nix;
  };
  ociContainers = {
    app = ./workloads/app/workload.nix;
  };
  hostServices = {
  };
  hostPorts = {
    tcp = [ 443 8080 9999 ];
    udp = [ 53 ];
  };
  secrets = {
  };
}
`
	if string(got) != want {
		t.Errorf("index.nix:\n%s\nwant:\n%s", got, want)
	}
}

func TestWorkloadRoundTrip(t *testing.T) {
	f := &StateFlake{Dir: t.TempDir()}
	if err := f.Init(); err != nil {
		t.Fatal(err)
	}
	content := "{ autoStart = true; }\n"
	if err := f.WriteWorkload("web", content); err != nil {
		t.Fatal(err)
	}
	got, err := f.ReadWorkload("web")
	if err != nil {
		t.Fatal(err)
	}
	if got != content {
		t.Errorf("got %q, want %q", got, content)
	}
	if err := f.RemoveWorkload("web"); err != nil {
		t.Fatal(err)
	}
	if _, err := f.ReadWorkload("web"); !os.IsNotExist(err) {
		t.Errorf("expected not-exist after remove, got %v", err)
	}
}

func TestValidateName(t *testing.T) {
	// Shared path-safety rule: charset + no leading/trailing dash, up to
	// 63 chars. Longer names (an OCI container may use them) are fine here;
	// the 11-char nspawn cap is a per-type concern, tested separately.
	long63 := strings.Repeat("a", 63)
	valid := []string{"web", "db-1", "a", "abcdefghijk", "abcdefghijkl", long63}
	invalid := []string{"", "-web", "web-", "Web", "web_1", long63 + "a", "a/b", "../etc"}
	for _, n := range valid {
		if err := ValidateName(n); err != nil {
			t.Errorf("ValidateName(%q) = %v, want nil", n, err)
		}
	}
	for _, n := range invalid {
		if err := ValidateName(n); err == nil {
			t.Errorf("ValidateName(%q) = nil, want error", n)
		}
	}
}

// TestContainerNameLimit covers the nixos-container-specific 11-char cap
// layered on top of the shared rule via the type's ValidateName.
func TestContainerNameLimit(t *testing.T) {
	wt, ok := Lookup(WorkloadTypeContainer)
	if !ok {
		t.Fatal("nixos-container type not registered")
	}
	if err := wt.ValidateName("abcdefghijk"); err != nil { // 11 chars: ok
		t.Errorf("ValidateName(11 chars) = %v, want nil", err)
	}
	if err := wt.ValidateName("abcdefghijkl"); err == nil { // 12 chars: too long
		t.Error("ValidateName(12 chars) = nil, want error")
	}

	// The OCI type accepts the longer name the container type rejects.
	oci, ok := Lookup(WorkloadTypeOCI)
	if !ok {
		t.Fatal("oci-container type not registered")
	}
	if err := oci.ValidateName("abcdefghijkl"); err != nil {
		t.Errorf("OCI ValidateName(12 chars) = %v, want nil", err)
	}
}
