package nix

import (
	"os"
	"path/filepath"
	"testing"
)

func TestInitIdempotent(t *testing.T) {
	f := &StateFlake{Dir: t.TempDir()}
	if err := f.Init(); err != nil {
		t.Fatal(err)
	}
	// A regenerated index must survive a second Init (service restart).
	if err := f.WriteIndex([]IndexEntry{{Name: "web", Type: WorkloadTypeContainer}}); err != nil {
		t.Fatal(err)
	}
	if err := f.Init(); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(f.Dir, "index.nix"))
	if err != nil {
		t.Fatal(err)
	}
	want := `# Generated by nixbox; do not edit.
{
  containers = {
    web = ./workloads/web/workload.nix;
  };
}
`
	if string(got) != want {
		t.Errorf("index.nix after re-init:\n%s\nwant:\n%s", got, want)
	}
}

func TestWriteIndex(t *testing.T) {
	f := &StateFlake{Dir: t.TempDir()}
	if err := f.Init(); err != nil {
		t.Fatal(err)
	}
	entries := []IndexEntry{
		{Name: "zeta", Type: WorkloadTypeContainer},
		{Name: "alpha", Type: WorkloadTypeContainer},
		{Name: "future", Type: "oci-container"}, // not yet supported: excluded
	}
	if err := f.WriteIndex(entries); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(f.Dir, "index.nix"))
	if err != nil {
		t.Fatal(err)
	}
	want := `# Generated by nixbox; do not edit.
{
  containers = {
    alpha = ./workloads/alpha/workload.nix;
    zeta = ./workloads/zeta/workload.nix;
  };
}
`
	if string(got) != want {
		t.Errorf("index.nix:\n%s\nwant:\n%s", got, want)
	}
}

func TestWorkloadRoundTrip(t *testing.T) {
	f := &StateFlake{Dir: t.TempDir()}
	if err := f.Init(); err != nil {
		t.Fatal(err)
	}
	content := "{ autoStart = true; }\n"
	if err := f.WriteWorkload("web", content); err != nil {
		t.Fatal(err)
	}
	got, err := f.ReadWorkload("web")
	if err != nil {
		t.Fatal(err)
	}
	if got != content {
		t.Errorf("got %q, want %q", got, content)
	}
	if err := f.RemoveWorkload("web"); err != nil {
		t.Fatal(err)
	}
	if _, err := f.ReadWorkload("web"); !os.IsNotExist(err) {
		t.Errorf("expected not-exist after remove, got %v", err)
	}
}

func TestValidateName(t *testing.T) {
	valid := []string{"web", "db-1", "a", "abcdefghijk"}
	invalid := []string{"", "-web", "web-", "Web", "web_1", "abcdefghijkl", "a/b", "../etc"}
	for _, n := range valid {
		if err := ValidateName(n); err != nil {
			t.Errorf("ValidateName(%q) = %v, want nil", n, err)
		}
	}
	for _, n := range invalid {
		if err := ValidateName(n); err == nil {
			t.Errorf("ValidateName(%q) = nil, want error", n)
		}
	}
}
