// Package nix implements nixbox's integration with the Nix toolchain:
// generation of the managed state flake, the rebuild pipeline, and
// expression validation.
//
// The state flake (<stateDir>/state) is a self-contained flake exporting
// nixosModules.default. The host flake references it as a path input; a
// rebuild picks up changes after `nix flake update nixbox-state`.
package nix

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// WorkloadTypeContainer is the only workload type in v1. Additional
// types (oci-container, microvm) plug in as new branches of the index
// and new static modules.
const WorkloadTypeContainer = "nixos-container"

const stateFlakeNix = `{
  description = "nixbox-managed workloads (generated; do not edit by hand)";

  outputs = { self }: {
    nixosModules.default = import ./modules/containers.nix;
  };
}
`

// A flake with no inputs still needs a lock file for path-input
// consumers; this is exactly what `nix flake lock` produces.
const stateFlakeLock = `{
  "nodes": {
    "root": {}
  },
  "root": "root",
  "version": 7
}
`

const containersModule = `{ lib, ... }:

let
  index = import ../index.nix;
in
{
  containers = lib.mapAttrs (name: path: import path) index.containers;

  # Host firewall ports declared by enabled workloads. Shared-namespace
  # containers serve on the host's network stack, so the port they listen
  # on must be opened here rather than inside the container. ` + "`or [ ]`" + ` keeps
  # this evaluating against index files generated before host ports existed.
  networking.firewall.allowedTCPPorts = index.hostPorts.tcp or [ ];
  networking.firewall.allowedUDPPorts = index.hostPorts.udp or [ ];
}
`

// StateFlake manages the on-disk layout of the generated flake.
type StateFlake struct {
	// Dir is the root of the state flake (<stateDir>/state).
	Dir string
}

// Init seeds the static files of the state flake. It is idempotent and
// never touches workloads/ or index.nix if they already exist, so it is
// safe to run on every service start.
func (f *StateFlake) Init() error {
	for _, d := range []string{f.Dir, filepath.Join(f.Dir, "modules"), filepath.Join(f.Dir, "workloads")} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			return err
		}
	}
	static := map[string]string{
		"flake.nix":              stateFlakeNix,
		"flake.lock":             stateFlakeLock,
		"modules/containers.nix": containersModule,
	}
	for name, content := range static {
		if err := writeFileAtomic(filepath.Join(f.Dir, name), []byte(content)); err != nil {
			return err
		}
	}
	// An index must always exist for the flake to evaluate.
	indexPath := filepath.Join(f.Dir, "index.nix")
	if _, err := os.Stat(indexPath); os.IsNotExist(err) {
		if err := f.WriteIndex(nil); err != nil {
			return err
		}
	}
	return nil
}

// IndexEntry is one enabled workload to expose to the host system.
type IndexEntry struct {
	Name  string
	Type  string
	Ports []HostPort // host firewall ports to open for this workload
}

// WriteIndex regenerates index.nix from the enabled workloads: the
// container path map plus the union of host ports every enabled workload
// asked to open, split by protocol.
func (f *StateFlake) WriteIndex(entries []IndexEntry) error {
	var containers []string
	tcpSeen, udpSeen := map[int]bool{}, map[int]bool{}
	var tcp, udp []int
	for _, e := range entries {
		if e.Type != WorkloadTypeContainer {
			continue
		}
		containers = append(containers, e.Name)
		for _, p := range e.Ports {
			switch p.Proto {
			case "udp":
				if !udpSeen[p.Port] {
					udpSeen[p.Port] = true
					udp = append(udp, p.Port)
				}
			default:
				if !tcpSeen[p.Port] {
					tcpSeen[p.Port] = true
					tcp = append(tcp, p.Port)
				}
			}
		}
	}
	sort.Strings(containers)
	sort.Ints(tcp)
	sort.Ints(udp)

	var b strings.Builder
	b.WriteString("# Generated by nixbox; do not edit.\n{\n  containers = {\n")
	for _, name := range containers {
		fmt.Fprintf(&b, "    %s = ./workloads/%s/workload.nix;\n", nixAttrName(name), name)
	}
	b.WriteString("  };\n  hostPorts = {\n")
	fmt.Fprintf(&b, "    tcp = %s;\n", nixIntList(tcp))
	fmt.Fprintf(&b, "    udp = %s;\n", nixIntList(udp))
	b.WriteString("  };\n}\n")
	return writeFileAtomic(filepath.Join(f.Dir, "index.nix"), []byte(b.String()))
}

// nixIntList renders a Nix list literal of integers, e.g. "[ 80 443 ]"
// or "[ ]" when empty.
func nixIntList(xs []int) string {
	if len(xs) == 0 {
		return "[ ]"
	}
	parts := make([]string, len(xs))
	for i, x := range xs {
		parts[i] = strconv.Itoa(x)
	}
	return "[ " + strings.Join(parts, " ") + " ]"
}

// WriteWorkload writes a workload's Nix expression to its slot in the
// state flake.
func (f *StateFlake) WriteWorkload(name, content string) error {
	if err := ValidateName(name); err != nil {
		return err
	}
	dir := filepath.Join(f.Dir, "workloads", name)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	return writeFileAtomic(filepath.Join(dir, "workload.nix"), []byte(content))
}

// ReadWorkload returns the current on-disk expression for a workload.
func (f *StateFlake) ReadWorkload(name string) (string, error) {
	if err := ValidateName(name); err != nil {
		return "", err
	}
	b, err := os.ReadFile(filepath.Join(f.Dir, "workloads", name, "workload.nix"))
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// RemoveWorkload deletes a workload's directory from the state flake.
// The caller must regenerate the index first so the flake never
// references a missing file.
func (f *StateFlake) RemoveWorkload(name string) error {
	if err := ValidateName(name); err != nil {
		return err
	}
	return os.RemoveAll(filepath.Join(f.Dir, "workloads", name))
}

// nameRe: systemd-nspawn creates a "ve-<name>" host interface for
// private networking; interface names cap at 15 bytes, leaving 11 for
// the container name. Same limit NixOS enforces on containers.<name>.
var nameRe = regexp.MustCompile(`^[a-z0-9]([a-z0-9-]{0,9}[a-z0-9])?$`)

func ValidateName(name string) error {
	if !nameRe.MatchString(name) {
		return fmt.Errorf("invalid workload name %q: must be 1-11 characters of [a-z0-9-], not starting or ending with -", name)
	}
	return nil
}

// nixAttrName quotes the attribute if it isn't a valid bare Nix
// identifier (e.g. names starting with a digit, or containing -).
func nixAttrName(name string) string {
	if regexp.MustCompile(`^[a-zA-Z_][a-zA-Z0-9_'-]*$`).MatchString(name) {
		return name
	}
	return `"` + name + `"`
}

// writeFileAtomic writes via a temp file + rename so a crash mid-write
// never leaves a truncated file for Nix to evaluate.
func writeFileAtomic(path string, data []byte) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), ".tmp-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Chmod(0o644); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}
